apiVersion: v1
kind: Service
metadata:
  name: playlist-service
spec:
  selector:
    app: playlist
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: playlist
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: playlist
    spec:
      containers:
      - name: playlist
        image: playlist:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000